#!/bin/bash

set -e

# Define the .env file path
ENV_FILE_PATH=".env"

# Clear the contents of the .env file
> "$ENV_FILE_PATH"

echo "AZURE_OPENAI_CHAT_DEPLOYMENT=$(azd env get-value AZURE_OPENAI_CHAT_DEPLOYMENT)" >> "$ENV_FILE_PATH"
echo "AZURE_OPENAI_CHAT_MODEL=$(azd env get-value AZURE_OPENAI_CHAT_MODEL)" >> "$ENV_FILE_PATH"
echo "AZURE_OPENAI_ENDPOINT=$(azd env get-value AZURE_OPENAI_ENDPOINT)" >> "$ENV_FILE_PATH"
echo "AZURE_TENANT_ID=$(azd env get-value AZURE_TENANT_ID)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_ACCOUNT=$(azd env get-value AZURE_COSMOSDB_ACCOUNT)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_DATABASE=$(azd env get-value AZURE_COSMOSDB_DATABASE)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_CONTAINER=$(azd env get-value AZURE_COSMOSDB_CONTAINER)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_USER_CONTAINER=$(azd env get-value AZURE_COSMOSDB_USER_CONTAINER)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_OAUTH_CONTAINER=$(azd env get-value AZURE_COSMOSDB_OAUTH_CONTAINER)" >> "$ENV_FILE_PATH"
echo "APPLICATIONINSIGHTS_CONNECTION_STRING=$(azd env get-value APPLICATIONINSIGHTS_CONNECTION_STRING)" >> "$ENV_FILE_PATH"
echo "MCP_AUTH_PROVIDER=$(azd env get-value MCP_AUTH_PROVIDER)" >> "$ENV_FILE_PATH"
KEYCLOAK_REALM_URL=$(azd env get-value KEYCLOAK_REALM_URL 2>/dev/null || echo "")
# Filter out ERROR messages from azd output (azd writes errors to stdout, not stderr)
if [[ "$KEYCLOAK_REALM_URL" == *ERROR:* ]]; then
  KEYCLOAK_REALM_URL=""
fi
if [ -n "$KEYCLOAK_REALM_URL" ]; then
  echo "KEYCLOAK_REALM_URL=${KEYCLOAK_REALM_URL}" >> "$ENV_FILE_PATH"
  KEYCLOAK_TOKEN_ISSUER=$(azd env get-value KEYCLOAK_TOKEN_ISSUER 2>/dev/null || echo "")
  if [[ "$KEYCLOAK_TOKEN_ISSUER" == *ERROR:* ]]; then
    KEYCLOAK_TOKEN_ISSUER=""
  fi
  if [ -n "$KEYCLOAK_TOKEN_ISSUER" ]; then
    echo "KEYCLOAK_TOKEN_ISSUER=${KEYCLOAK_TOKEN_ISSUER}" >> "$ENV_FILE_PATH"
  fi
fi
ENTRA_PROXY_AZURE_CLIENT_ID=$(azd env get-value ENTRA_PROXY_AZURE_CLIENT_ID 2>/dev/null || echo "")
if [[ "$ENTRA_PROXY_AZURE_CLIENT_ID" == *ERROR:* ]]; then
  ENTRA_PROXY_AZURE_CLIENT_ID=""
fi
if [ -n "$ENTRA_PROXY_AZURE_CLIENT_ID" ]; then
  echo "ENTRA_PROXY_AZURE_CLIENT_ID=${ENTRA_PROXY_AZURE_CLIENT_ID}" >> "$ENV_FILE_PATH"
  ENTRA_PROXY_AZURE_CLIENT_SECRET=$(azd env get-value ENTRA_PROXY_AZURE_CLIENT_SECRET 2>/dev/null || echo "")
  if [[ "$ENTRA_PROXY_AZURE_CLIENT_SECRET" == *ERROR:* ]]; then
    ENTRA_PROXY_AZURE_CLIENT_SECRET=""
  fi
  echo "ENTRA_PROXY_AZURE_CLIENT_SECRET=${ENTRA_PROXY_AZURE_CLIENT_SECRET}" >> "$ENV_FILE_PATH"
  ENTRA_PROXY_MCP_SERVER_BASE_URL=$(azd env get-value ENTRA_PROXY_MCP_SERVER_BASE_URL 2>/dev/null || echo "")
  if [[ "$ENTRA_PROXY_MCP_SERVER_BASE_URL" == *ERROR:* ]]; then
    ENTRA_PROXY_MCP_SERVER_BASE_URL=""
  fi
  echo "ENTRA_PROXY_MCP_SERVER_BASE_URL=${ENTRA_PROXY_MCP_SERVER_BASE_URL}" >> "$ENV_FILE_PATH"
fi
echo "MCP_ENTRY=$(azd env get-value MCP_ENTRY)" >> "$ENV_FILE_PATH"
echo "MCP_SERVER_URL=$(azd env get-value MCP_SERVER_URL)" >> "$ENV_FILE_PATH"
echo "KEYCLOAK_MCP_SERVER_BASE_URL=$(azd env get-value KEYCLOAK_MCP_SERVER_BASE_URL)" >> "$ENV_FILE_PATH"
echo "API_HOST=azure" >> "$ENV_FILE_PATH"
